version: "3.8"

services:
  mattermost:
    image: mattermost/mattermost-preview
    volumes:
      - ./config:/mattermost/config
    ports:
      - "8065:8065"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000

  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mattermost
      - POSTGRES_USER_PASSWORD=mattermost
      - POSTGRES_DB=mattermost
