[tool.poetry]
name = "randomcoffeebot"
version = "0.1.0"
description = ""
authors = ["Павел Смирнов <baksbannysmirnov@yandex.ru>"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"
asyncpg = "^0.28.0"
sqlalchemy = "^2.0.19"
dependency-injector = "^4.41.0"
alembic = "^1.11.1"


[tool.poetry.group.dev.dependencies]
markupsafe = "^2.1.3"
greenlet = "^2.0.2"
python-dotenv = "^1.0.0"
pre-commit = "^3.3.2"
mako = "^1.2.4"
typing-extensions = "^4.7.1"
flake8 = "^6.0.0"
black = "^23.7.0"
isort = "^5.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
