[tool.poetry]
name = "randomcoffeebot"
version = "0.1.0"
description = ""
authors = ["Павел Смирнов <baksbannysmirnov@yandex.ru>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
alembic = "1.7.7"
greenlet = "2.0.2"
mako = "1.2.4"
markupsafe = "2.1.3"
python-dotenv = "1.0.0"
sqlalchemy = "2.0.19"
typing-extensions = "4.7.1"
annotated-types = "0.5.0"
pydantic = "1.10.4"
pydantic-core = "2.3.0"
asyncpg = "^0.28.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
