version: "3.11"

services:
  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=random_coffee_db
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
