version: "3.11"

services:
  db:
    container_name: "db_bot"
    image: postgres:15.3-alpine3.18
    restart: always
    env_file: .env

  bot:
    container_name: "bot_mattermost"
    image: ghcr.io/studio-yandex-practicum/randomcoffeebot:stage
    env_file: .env
    ports:
      - "8579:8579"
    restart: always
    depends_on:
      - db

volumes:
  db:
