version: "3.11"

services:
  db:
    container_name: "db_bot"
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  bot:
    container_name: "bot_mattermost"
    build:
      context: ../
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    depends_on:
      - db

volumes:
  db:
