"""empty message

Revision ID: b4b4c68b8aa3
Revises:
Create Date: 2023-08-10 12:35:25.993047

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b4b4c68b8aa3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column(
            "status", sa.Enum("IN_MEETING", "WAITING_MEETING", "NOT_INVOLVED", name="statusenum"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "usersmatch",
        sa.Column("matched_user_one", sa.Integer(), nullable=False),
        sa.Column("matched_user_two", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("ONGOING", "SUCCESSFUL", "UNSUCCESSFUL", name="matchstatusenum"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.ForeignKeyConstraint(
            ["matched_user_one"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matched_user_two"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usersmatch")
    op.drop_table("users")
    # ### end Alembic commands ###
