"""empty message

Revision ID: 6d584f53f8cf
Revises: cebca1c19787
Create Date: 2023-11-28 13:15:38.416597

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d584f53f8cf"
down_revision = "cebca1c19787"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
