"""add match_review

Revision ID: abb6775f7512
Revises: 6d584f53f8cf
Create Date: 2023-12-04 20:54:36.381591

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "abb6775f7512"
down_revision = "6d584f53f8cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_review",
        sa.Column("usersmatch_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "user_answer", sa.Enum("IS_COMPLETE", "IS_NOT_COMPLETE", name="matchreviewanswerenum"), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usersmatch_id"],
            ["usersmatch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("match_review")
    op.execute("drop type matchreviewanswerenum")
    # ### end Alembic commands ###
